# Tests that dict length cannot be modified during iteration.
# @error error: dict length changed during iteration (was 3, became 2)
# @error stack traceback (most recent call first):
# @error     <FFI>                        DictIter.has_next
# @error     {file}:{:LINE}:1  <main>

let dict = ["a": 1, "b": 2, "c": 3]
for (key, value) in dict.iter do  # @line LINE
    dict.remove(key)
end
